### PR TITLE
Fix Issue #153 : Added an option to overlay or underlay the Grid

### LINKED ISSUE #153: Grid overlaps chart
image

Is there a work around for this?

### PR DESCRIPTION
**Pull request by sartaj10**
Fixes #153

### CODE REVIEW

File: src/components/TimeAxis.js [hunk 1]
```diff
@@ -144,12 +144,14 @@ export default class TimeAxis extends React.Component {
 
 TimeAxis.defaultProps = {
   showGrid: false,
+  showGridPosition: "over",
```
Comment (pjm17971) [inline src/components/TimeAxis.js]: I don't think `showGridPosition` is needed here.

**Comment by sartaj10** [comment]
Made the required changes.
